### ISSUE TITLE
Clean Up, delete extra blank lines

### ISSUE THREAD

**Issue by jennylia** [jennylia/partner#4]
Delete extra blank lines in:
https://github.com/jennylia/partner/blob/master/app/client/templates/match_list/match_list.js

**Comment by christinepham** [comment]
My pr addresses this as well, not sure which lines you wanted to get rid of so I deleted a few obvious ones for you. Hope that helps!

**Comment by jennylia** [comment]
@christinepham Thanks again! It helps tremendously
